#!/bin/sh
# /etc/hotplug.d/net/05-usb-tether-rename
# Name USB-tethering interfaces by the hub port they sit on, so wan1/2/3
# always mean the same phone regardless of enumeration order.
# Hub = USB3.1 hub on the TCSS xHCI (bus 2, port 1): 2-1.1 / 2-1.2 / 2-1.3
[ "$ACTION" = "add" ] || exit 0
case "$INTERFACE" in usb[0-9]*) ;; *) exit 0 ;; esac
case "$DEVPATH" in
	*/usb2/2-1/2-1.1/*) new="usb-docomo" ;;
	*/usb2/2-1/2-1.2/*) new="usb-au" ;;
	*/usb2/2-1/2-1.3/*) new="usb-softbank" ;;
	*) exit 0 ;;
esac
[ "$INTERFACE" = "$new" ] && exit 0
ip link set "$INTERFACE" down 2>/dev/null
if ip link set "$INTERFACE" name "$new" 2>/dev/null; then
	logger -t usb-tether "renamed $INTERFACE -> $new ($DEVPATH)"
else
	logger -t usb-tether "rename $INTERFACE -> $new failed"
fi
